# Generated by Django 5.2.4 on 2025-07-09 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
        ('clubs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-created_at'], 'verbose_name': 'Announcement', 'verbose_name_plural': 'Announcements'},
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='announcer',
        ),
        migrations.AddField(
            model_name='announcement',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_announcements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='club',
            field=models.ForeignKey(blank=True, help_text='Leave blank for a global announcement. Select a club for a club-specific announcement.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='club_announcements', to='clubs.club'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='is_global',
            field=models.BooleanField(default=True, help_text='Check if this announcement is for all users.'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
